apply plugin: 'com.android.library'
apply plugin: 'expo-module'
apply plugin: 'org.jetbrains.kotlin.android'

group = 'com.touchgrassmodule'
version = '1.0.0'

android {
    namespace "com.touchgrassmodule"

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    lintOptions {
        abortOnError false
    }
}
